" General config.
syn on
set noeb vb t_vb=
set guioptions-=aegimrLtT
set nu
set mouse=a
set smarttab
set modeline
set ruler
set history=100
set nowrap
set title
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set shiftwidth=4
set softtabstop=4
set backspace=indent,eol,start
set timeout timeoutlen=5000 ttimeoutlen=100
set background=dark
" Swapdir and undo dir creation.
set directory=$HOME/.config/nvim/swapdir
set undofile
set undodir=$HOME/.config/nvim/undodir
set undolevels=1000
set undoreload=10000
" Leader definition.
let mapleader=";"
let localleader="\\"

" Esc remaping.
inoremap kj <esc>
" Hide coloration of found words.
map <C-C> :nohlsearch<CR>
