autoload -U compinit
compinit

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
USER=$(whoami)
UNAME=$(uname)

if [[ $USER != "root" ]]; then
	if [[ $UNAME == "Darwin" ]]; then
		alias ls='ls -G' 
		export PATH=~/.brew/opt/fzf/bin:$PATH
		export PATH=~/.brew/bin:$PATH
		precmd() {

		}
	else
		# launch the default xorg window manager
		[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx -- vt1 &> /dev/null
		xset b off

		# use this for a i3 with wayland alternative
		#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
		#	export XKB_DEFAULT_LAYOUT=us
		#	export XKB_DEFAULT_VARIANT=altgr-intl
		#	export XKB_DEFAULT_OPTIONS=grp:win_space_toggle
		#	exec sway
		#fi
		export PATH=/usr/lib/llvm-7.0/bin:$PATH
		alias ls='ls --color'
		# copy/paste
		alias open='xdg-open'
	fi

#	if command -v tmux>/dev/null; then
	#		[[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux -2
	#	fi
fi

# colored man
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal
export TERM=xterm-256color

set +o noclobber

# ls aliases
alias ll='ls -l'
alias la='ls -a'
alias l='ls'

# vim alias
alias vim='vim'

# systemctl aliases
alias ss='systemctl status'
alias lus='systemctl list-units --type=service'

# ps aliases
alias pssh='ps faux | grep sshd'
alias psftp='ps faux | grep ftp'

# reset shell
alias esl='exec $SHELL -l'

# emacs aliases
alias enw='emacs -nw'
alias em='emacs'
alias ec='emacsclient -n'

# apvlv aliases
alias pdf='apvlv'

# Incremental search is elite!
bindkey -M vicmd "?" history-incremental-search-backward
bindkey -M vicmd "/" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "??" history-beginning-search-backward
bindkey -M vicmd "//" history-beginning-search-forward

bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey -M viins "kj" vi-cmd-mode
export PATH="$HOME/.cargo/bin:$PATH"
export PATH=~/bin:$PATH
