#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

UNAME=$(uname)
if [[ $UNAME == "Darwin" ]]; then
	alias ls='ls -G' 
	export PATH=~/.brew/bin/:$PATH
else
	[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx -- vt1 &> /dev/null
	if command -v tmux>/dev/null; then
	  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux -2
	fi
	alias ls='ls --color'
	# copy/paste
	alias open='xdg-open'

fi

#bind -m vi-insert "\C-l":clear-screen

# colored man
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal
export EDITOR="nvim"
export VISUAL="nvim"
export TERM=xterm-256color

alias vim='nvim'
alias vi='nvim'

# ls aliases
alias ll='ls -l'
alias la='ls -a'
alias l='ls'

# systemctl aliases
alias ss='systemctl status'
alias lus='systemctl list-units --type=service'

# ps aliases
alias pssh='ps faux | grep sshd'
alias psftp='ps faux | grep ftp'

# reset shell
alias esl='exec $SHELL -l'

# emacs aliases
alias em='emacs'
alias ec='emacsclient -n'

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey -M viins "kj" vi-cmd-mode
