source $HOME/.config/nvim/config/plugins.vim
source $HOME/.config/nvim/config/nvim.vim
source $HOME/.config/nvim/config/deoplete.vim
source $HOME/.config/nvim/config/ale.vim
source $HOME/.config/nvim/config/ctrlp.vim
source $HOME/.config/nvim/config/nerdtree.vim
source $HOME/.config/nvim/config/fugitive.vim
source $HOME/.config/nvim/config/easymotion.vim
source $HOME/.config/nvim/config/tagbar.vim
